#!/bin/bash

BACKUP_SCRIPTS_DIR="$EIP_HOME_DIR/scripts/db-backup"
SETUP_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo "STARTING THE INSTALLATION PROCESS USING STUFF FROM $SETUP_DIR"

if [ -d "$BACKUP_SCRIPTS_DIR" ]; then
   	echo "THE BACKUP SCRIPTS DIR EXISTS"
else
    	echo "THE BACKUP SCRIPTS DIRECTORY DOESN'T EXISTS"
    	echo "THE BACKUP SCRIPTS DIRECTORY IS BEING CREATED"

	mkdir -p $BACKUP_SCRIPTS_DIR

 	echo "THE BACKUP SCRIPTS DIRECTORY WAS CREATED"
fi

cp $SETUP_DIR/scripts/* -r $BACKUP_SCRIPTS_DIR

$SETUP_DIR/install_crons.sh $EIP_HOME_DIR

echo "INSTALLATION COMPLETED"
