#OPENMRS DB CONF
export OPENMRS_DB_NAME=
export OPENMRS_DB_USER=
export OPENMRS_DB_PASSWORD=
export OPENMRS_DB_CONTAINER=
export OPENMRS_CENTRAL_APP_CONTAINER=

#DBSYNC DB CONF
export MGT_DB_NAME=
export MGT_DB_USER=
export MGT_DB_PASSWORD=
export MGT_DB_CONTAINER=
export DBSYNC_CENTRAL_APP_CONTAINER=

#EIP HOME
export EIP_HOME_DIR="/home/mufume"
