#!/bin/bash
# generic script for backup the dbsync mgt and openmrs databases
#

CONFIG_FILE=$1

. $CONFIG_FILE

SCRIPT_LOCATION=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

#STOP THE CONTAINERS FOR APPS (DBSYNC_CENTRAL AND OPENMRS_CENTRAL)
docker stop $DBSYNC_CENTRAL_CONTAINER
echo "CONTAINER $DBSYNC_CENTRAL_CONTAINER STOPPED"

docker stop $OPENMRS_CENTRAL_CONTAINER
echo "CONTAINER $OPENMRS_CENTRAL_CONTAINER STOPPED"


#START THE BACKUP EXECUTION
echo "RUNNING OPENMRS BACKUP"
$SCRIPT_LOCATION/bkp_openmrs_db.sh $CONFIG_FILE
echo "FINISHED OPENMRS BACKUP"

echo "RUNNING DBSYNC_MGT BACKUP"
$SCRIPT_LOCATION/bkp_dbsync_mgt_db.sh $CONFIG_FILE
echo "FINISHED DBSYNC_MGT BACKUP"


#RESTART THE CONTAINERS FOR APPS (OPENMRS_CENTRAL AND DBSYNC_CENTRAL)
echo "STARTING CONTAINER $OPENMRS_CENTRAL_CONTAINER"
docker start $OPENMRS_CENTRAL_CONTAINER
echo "CONTAINER $OPENMRS_CENTRAL_CONTAINER STARTED"

echo "STARTING CONTAINER $DBSYNC_CENTRAL_CONTAINER"
docker start $DBSYNC_CENTRAL_CONTAINER
echo "CONTAINER $DBSYNC_CENTRAL_CONTAINER STARTED"


