#!/bin/bash
# generic script for backup the dbsync mgt and openmrs databases
#

CONFIG_FILE=$1

. $CONFIG_FILE

SCRIPT_LOCATION=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

OPENMRS_APP_CONTAINER=$OPENMRS_CENTRAL_APP_CONTAINER
DBSYNC_APP_CONTAINER=$DBSYNC_CENTRAL_APP_CONTAINER
LOG_DIR=$EIP_HOME_DIR/shared/logs/application_containers

#STOP THE CONTAINERS FOR APPS (DBSYNC_CENTRAL AND OPENMRS_CENTRAL)
docker stop $DBSYNC_APP_CONTAINER

LOG_DIR_DBSYNC=$LOG_DIR/$DBSYNC_APP_CONTAINER

if [ -d "$LOG_DIR_DBSYNC" ]; then
  echo "THE LOG DIR $LOG_DIR_DBSYNC EXISTS" | tee -a $LOG_DIR_DBSYNC/$DBSYNC_APP_CONTAINER.log
else
  mkdir -p $LOG_DIR_DBSYNC
  echo "THE LOG DIR $LOG_DIR_DBSYNC WAS CREATED" | tee -a $LOG_DIR_DBSYNC/$DBSYNC_APP_CONTAINER.log
fi
echo "$(date '+%Y-%m-%d %H:%M:%S') CONTAINER $DBSYNC_APP_CONTAINER STOPPED" | tee -a $LOG_DIR_DBSYNC/$DBSYNC_APP_CONTAINER.log



docker stop $OPENMRS_APP_CONTAINER

LOG_DIR_OPENMRS=$LOG_DIR/$OPENMRS_APP_CONTAINER

if [ -d "$LOG_DIR_OPENMRS" ]; then
  echo "THE LOG DIR $LOG_DIR_OPENMRS EXISTS" | tee -a $LOG_DIR_OPENMRS/$OPENMRS_APP_CONTAINER.log
else
  mkdir -p $LOG_DIR_OPENMRS
  echo "THE LOG DIR $LOG_DIR_OPENMRS WAS CREATED" | tee -a $LOG_DIR_OPENMRS/$OPENMRS_APP_CONTAINER.log
fi
echo "$(date '+%Y-%m-%d %H:%M:%S') CONTAINER $OPENMRS_APP_CONTAINER STOPPED" | tee -a $LOG_DIR_OPENMRS/$OPENMRS_APP_CONTAINER.log


#START THE BACKUP EXECUTION
echo "RUNNING OPENMRS BACKUP"
$SCRIPT_LOCATION/bkp_openmrs_db.sh $CONFIG_FILE
echo "FINISHED OPENMRS BACKUP"

echo "RUNNING DBSYNC_MGT BACKUP"
$SCRIPT_LOCATION/bkp_dbsync_mgt_db.sh $CONFIG_FILE
echo "FINISHED DBSYNC_MGT BACKUP"


#RESTART THE CONTAINERS FOR APPS (OPENMRS_CENTRAL AND DBSYNC_CENTRAL)

echo "STARTING CONTAINER $OPENMRS_APP_CONTAINER" | tee -a $LOG_DIR_OPENMRS/$OPENMRS_APP_CONTAINER.log
docker start $OPENMRS_APP_CONTAINER
echo "$(date '+%Y-%m-%d %H:%M:%S') CONTAINER $OPENMRS_APP_CONTAINER STARTED" | tee -a $LOG_DIR_OPENMRS/$OPENMRS_APP_CONTAINER.log

echo "STARTING CONTAINER $DBSYNC_APP_CONTAINER" | tee -a $LOG_DIR_DBSYNC/$DBSYNC_APP_CONTAINER.log
docker start $DBSYNC_APP_CONTAINER
echo "$(date '+%Y-%m-%d %H:%M:%S') CONTAINER $DBSYNC_APP_CONTAINER STARTED" | tee -a $LOG_DIR_DBSYNC/$DBSYNC_APP_CONTAINER.log


