#!/bin/bash
# specific script for backup the openmrs database
#

DB_CONTAINER=$OPENMRS_DB_CONTAINER
DB_USER=$OPENMRS_DB_USER
DB_PASSWORD=$OPENMRS_DB_PASSWORD
DB_NAME=$OPENMRS_DB_NAME
BKP_HOME_DIR_OPENMRS=$EIP_HOME_DIR


echo "STARTING THE EXECUTION OF BKP_DB.SH SCRIPT"
$EIP_HOME_DIR/scripts/db-backup/bkp_db.sh $DB_CONTAINER $DB_USER $DB_PASSWORD $DB_NAME $BKP_HOME_DIR_OPENMRS